module.exports.HTTP_STATUS = {
	BAD_REQUEST: 400,
	UNAUTHORISED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	CONFLICT: 409,

	INTERNAL_SERVER_ERROR: 500,
	GATEWAY_TIMEOUT: 504
};

module.exports.ERRORS = {
	STATUS: 1,
	CLIENT_ERROR: 2,
	SERVER_ERROR: 3,
	DB_ERROR: 4
};